import pandas as pd

# Load the data generated by ingest.py file
df = pd.read_csv("data_raw.csv")
#data before preprocessing
print(df.head())

# TASK 1: CLEANING (3 Sub-tasks) ---

# 1. Remove duplicate rows from the dataset
df = df.drop_duplicates()

# 2. Handle missing values (fillna)
# Fill numeric columns with 0 and categorical with 'Unknown'
df = df.fillna({
    'popularity': 0,
    'track_name': 'Unknown'
})

# 3. Data type conversion 
# Ensure 'popularity' is actually an integer
df['popularity'] = df['popularity'].astype(int)


# TASK 2: DISCRETIZATION

# Turning 'popularity' (0-100) into categories
bins = [0, 33, 66, 100]
labels = ['Indie/Niche', 'Mainstream', 'Viral']

df['pop_level'] = pd.cut(df['popularity'], bins=bins, labels=labels, include_lowest=True)

# Saving the preprocessed dataset
df.to_csv("data_processed.csv", index=False)
print("Preprocessing complete. 3 cleaning tasks and discretization applied.")
#data after preprocessing
print(df.head())